### ISSUE TITLE
Improving Code Quality

### ISSUE THREAD

**Issue by huzaifa-99** [abrahamjuliot/creepjs#184] opened 2022-06-19 18:23 UTC
Would be a good idea to do these (some are for better readability)
- [ ] Use strict equality checks, replacing abstract checks
- [ ] Scoping variables, removing shallow variables
- [ ] Removing unused code (declarations, imports etc.)
- [ ] Removing nested ternary operators

Probably doing some linting setup with pre-commit hooks would be better.

Thanks.

**Comment by abrahamjuliot** [comment] 2022-06-19 19:31
Good tips. Yes, linting, minification, and even use of TypeScript would greatly improve quality. At some point, I may add all this, but I don't like the idea of making this production ready code. 

- I'm not strict about `===` except where strict equality is necessary or when input is unknown. I prefer not using it everywhere (it removes the work of asking why or why not)
- Not sure what/where you are referencing shallow variables.
- Minification or production ready code is not a goal. Everything here is mostly experimental and for research.
- I totally agree, nested ternary is bad for a welcoming readability. Personally, I don't mind them at all. Some code concepts are difficult to parse and reason with by design.

closing for now, but I will tag revisit

**Closed by abrahamjuliot** 2022-06-19 19:31 UTC
