### ISSUE TITLE
400 error code for fp result request

### ISSUE THREAD

**Issue by promotorov** [abrahamjuliot/creepjs#167] opened 2022-01-07 15:58 UTC
Trying to test fp results for emulated chrome via CDP on windows, but always got 400 code error for this request:
https://creepjs-api.web.app/fp?id=f4e91f77a03f38f66e92984e12ec33d846ef674b92cf72e08be7ec42bea24c77&subId=bffe574f01af4926f5d8e7bc3903484f793bf7aa34cde77b74fcc95f25711152&hasTrash=false&hasLied=false&hasErrors=false

![image](https://user-images.githubusercontent.com/18381389/148570342-b0ed69db-345f-47b9-848e-24e314c83589.png)

**Comment by abrahamjuliot** [comment] 2022-01-07 22:15
I locked requests to select origins, but you can simulate fetch requests in dev tools or from the console on the creepjs github page. I might open it up to localhost origins in the future.

I hope this is helpful

```js
await fetch(url).then(res => res.json())
```

**Comment by abrahamjuliot** [comment] 2022-01-09 17:02
Closing, but feel free to discuss

**Closed by abrahamjuliot** 2022-01-09 17:02 UTC
Labels: invalid, question

**Comment by HMaker** [comment] 2022-06-02 15:28
@abrahamjuliot I still get 400 Bad Request error when testing creepjs against tampered browser. Is that by design or a server error? I test at https://abrahamjuliot.github.io/creepjs/

**Comment by HMaker** [comment] 2022-06-09 18:31
> @HMaker yes, that's by design. Unknown origins, including localhost, are not supported.

I am accessing https://abrahamjuliot.github.io/creepjs/ , it's not localhost. Also the 400 Bad Request doesn't happen for vanilla browsers, only for the tampareded one. Both browsers have same version. So looks like the server returns 400 when the browser is tampered, but it should return HTTP 200 and display the tampering detection on the report, no?

**Comment by HMaker** [comment] 2022-06-09 19:40
It's not custom build, I use official Chrome and tamper browser APIs at JS level only.

**Comment by abrahamjuliot** [comment] 2022-07-14 02:29
I see. Sounds like it's resolved now. Good news I hope.

**Comment by wilsonssss** [comment] 2023-11-10 13:48
still being 400 from chromium with flag --disable-web-security
